name: Build and Release EXE

on:
  workflow_dispatch: # 支持在 GitHub 网页手动点击运行


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出源码
      uses: actions/checkout@v4

    - name: 编译 Release 可执行文件 (.NET 4.7.2)
      run: |
        dotnet build CloudPatchTool.csproj -c Release

    - name: 上传构建产物 (EXE)
      uses: actions/upload-artifact@v4
      with:
        name: 云管家补丁工具-Net472
        path: bin/Release/net472/云管家补丁工具.exe
